"""
Constants and Enums for the Revenue Recovery Intelligence Engine.
"""

from enum import Enum


class Environment(str, Enum):
    TEST = "test"
    LIVE = "live"
    SIMULATION = "simulation"


class EventType(str, Enum):
    # Payments
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAYMENT_REFUNDED = "PAYMENT_REFUNDED"

    # Checkout
    CHECKOUT_STARTED = "CHECKOUT_STARTED"
    PAYMENT_INITIATED = "PAYMENT_INITIATED"
    CHECKOUT_ABANDONED = "CHECKOUT_ABANDONED"

    # Subscriptions
    SUBSCRIPTION_CREATED = "SUBSCRIPTION_CREATED"
    SUBSCRIPTION_ACTIVE = "SUBSCRIPTION_ACTIVE"
    SUBSCRIPTION_PAYMENT_FAILED = "SUBSCRIPTION_PAYMENT_FAILED"
    SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED"
    SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED"

    # Invoices
    INVOICE_CREATED = "INVOICE_CREATED"
    INVOICE_PAID = "INVOICE_PAID"
    INVOICE_OVERDUE = "INVOICE_OVERDUE"

    # Mandates
    MANDATE_CREATED = "MANDATE_CREATED"
    MANDATE_ACTIVE = "MANDATE_ACTIVE"
    MANDATE_FAILED = "MANDATE_FAILED"

    # Recovery Lifecycles
    RECOVERY_ATTEMPTED = "RECOVERY_ATTEMPTED"
    RECOVERY_SUCCESS = "RECOVERY_SUCCESS"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    RECOVERY_STOPPED = "RECOVERY_STOPPED"
    RECOVERY_ESCALATED = "RECOVERY_ESCALATED"

    # System / Other
    UNKNOWN = "UNKNOWN"
    NON_RECOVERABLE = "NON_RECOVERABLE"


class AgentType(str, Enum):
    PAYMENT_FAILURE = "PaymentFailureAgent"
    CHECKOUT_ABANDONMENT = "CheckoutAbandonmentAgent"
    SUBSCRIPTION_RECOVERY = "SubscriptionRecoveryAgent"
    OVERDUE_RECEIVABLE = "OverdueReceivableAgent"
    ORCHESTRATOR = "RecoveryOrchestrator"


class RecoveryActionType(str, Enum):
    IMMEDIATE_RETRY = "IMMEDIATE_RETRY"
    DELAYED_RETRY = "DELAYED_RETRY"
    SEND_PAYMENT_REMINDER = "SEND_PAYMENT_REMINDER"
    SEND_PAYMENT_METHOD_UPDATE = "SEND_PAYMENT_METHOD_UPDATE"
    SEND_CHECKOUT_RECOVERY = "SEND_CHECKOUT_RECOVERY"
    GENERATE_PAYMENT_LINK = "GENERATE_PAYMENT_LINK"
    SEND_PERSONALIZED_MESSAGE = "SEND_PERSONALIZED_MESSAGE"
    START_VOICE_RECOVERY = "START_VOICE_RECOVERY"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"
    SCHEDULE_DUNNING_STEP = "SCHEDULE_DUNNING_STEP"
    PROGRESSIVE_FOLLOWUP = "PROGRESSIVE_FOLLOWUP"
    WAIT = "WAIT"
    STOP = "STOP"


class CommunicationChannel(str, Enum):
    SMS = "SMS"
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    VOICE = "VOICE"
    IN_APP = "IN_APP"
    NONE = "NONE"


class PolicyVerdictStatus(str, Enum):
    APPROVED = "APPROVED"
    MODIFIED = "MODIFIED"
    BLOCKED = "BLOCKED"
    ESCALATED = "ESCALATED"


class LanguagePreference(str, Enum):
    ENGLISH = "en"
    HINGLISH = "hinglish"
    HINDI = "hi"


class FailureCategory(str, Enum):
    TRANSIENT_BANK_TIMEOUT = "TRANSIENT_BANK_TIMEOUT"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    EXPIRED_OR_BLOCKED_CARD = "EXPIRED_OR_BLOCKED_CARD"
    MANDATE_REJECTED = "MANDATE_REJECTED"
    USER_CANCELLED = "USER_CANCELLED"
    INACTIVITY_DROPOFF = "INACTIVITY_DROPOFF"
    UNKNOWN = "UNKNOWN"
